### ISSUE TITLE
Problem with repeatmasker modules

### ISSUE THREAD

**Issue by jcerca** [clemgoub/dnaPipeTE#42]
Dear dnaPipeTE designers -I really look forward to running this pipeline and identify TEs on my popgen-level dataset. It is just what I needed.

I managed to install it, but keep getting an error when trying the test data.

Command
```
module load Java/1.8.0_212  # Gettting java
module load Bowtie2/2.4.1-GCC-9.3.0 ## and bowtie2

conda activate DNApipeTE
conda install -c conda-forge perl-text-soundex # This installed the module needed.
cpan text::soundex # This installed the module needed..

PERL5LIB=/cluster/projects/nn9408k/cerca/conda/envs/DNApipeTE/bin/perl:$PERL5LIB

python3 ./dnaPipeTE.py -input ./test/test_dataset.fastq -output ./tmp -genome_size 2000000 -genome_coverage 0.5 -sample_number 2
```

Error:
```
Can't locate Text/Soundex.pm in @INC (@INC contains: /cluster/home/josece/local_bin/dnaPipeTE/bin/RepeatMasker /cluster/projects/nn9408k/cerca/conda/envs/DNApipeTE/bin/perl /node/lib/perl5 /cluster/lib/perl5/x86_64-linux-thread-multi /cluster/lib/perl5 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /cluster/home/josece/local_bin/dnaPipeTE/bin/RepeatMasker/Taxonomy.pm line 83.
BEGIN failed--compilation aborted at /cluster/home/josece/local_bin/dnaPipeTE/bin/RepeatMasker/Taxonomy.pm line 83.
Compilation failed in require at /cluster/home/josece/local_bin/dnaPipeTE/bin/RepeatMasker/RepeatMasker line 313.
BEGIN failed--compilation aborted at /cluster/home/josece/local_bin/dnaPipeTE/bin/RepeatMasker/RepeatMasker line 313.
Traceback (most recent call last):
  File "./dnaPipeTE.py", line 698, in <module>
    RepeatMasker(config['DEFAULT']['RepeatMasker'], args.RepeatMasker_library, args.RM_species, args.cpu, args.output_folder, args.RM_threshold)
  File "./dnaPipeTE.py", line 381, in __init__
    self.repeatmasker_run()
  File "./dnaPipeTE.py", line 400, in repeatmasker_run
    with open(self.output_folder+"/Trinity.fasta.out", 'r') as trinity_handle:
FileNotFoundError: [Errno 2] No such file or directory: './tmp/Trinity.fasta.out'
```

I see this is a common repeatMasker error, however, I tried everything on google and I can't get it working. Would you happen to know how to sovle this? I have no sudo rights.

**Comment by jcerca** [comment]
Solved :)

I needed to feed it the perl libraries:
```
module load Java/1.8.0_212 # loading Java
module load Bowtie2/2.4.1-GCC-9.3.0 # loading Bowtie2
conda activate dnaPipeTE # getting soundex
PERL5LIB=/cluster/projects/nn9408k/cerca/conda/envs/DNApipeTE/lib/site_perl/5.26.2/:$PERL5LIB ### poiting out to the Soundex library
python3 ./dnaPipeTE.py -input ./test/test_dataset.fastq -output ./tmp -genome_size 2000000 -genome_coverage 0.5 -sample_number 2
```

This worked. My problem is that I hadn't pointed to the right perl library. If you use conda to install a module, look for the module somewhere around:
`/path/to/conda/envs/envname/lib/site_perl/*/`
